# Generated by Django 4.2.4 on 2023-09-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("df_model_actions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serveraction",
            name="python_code",
        ),
        migrations.AddField(
            model_name="serveraction",
            name="context",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="serveraction",
            name="executable_action",
            field=models.TextField(
                default="",
                help_text="It can be python code, python function or celery task",
            ),
        ),
        migrations.AddField(
            model_name="serveraction",
            name="type",
            field=models.CharField(
                choices=[
                    ("python_code", "Python Code"),
                    ("python_function", "Python Function"),
                    ("celery_task", "Celery Task"),
                ],
                default="python_code",
                max_length=32,
            ),
        ),
    ]
