# Generated by Django 4.2.4 on 2023-08-16 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "python_code",
                    models.TextField(
                        help_text="Python code. Allowed variables: instance"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelAction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("on_creation", "On Creation"),
                            ("on_update", "On Update"),
                            ("on_deletion", "On Deletion"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "condition",
                    models.TextField(
                        blank=True,
                        help_text="Python code. If it returns False, the action is not executed.Allowed variable: instance",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_actions",
                        to="df_model_action.serveraction",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_actions",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
